#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.local"   # this repo's local-dev env file (see .env.example)
VERCEL="npx vercel"

banner "Supabase setup"

# ── Stage 1: create the project ─────────────────────────────────────────
stage "Create the Supabase project"
say "This provisions the Postgres database that backs both the app's own"
say "tables and Better Auth's tables (docs/plan.md §4/§9)."
open_url "https://supabase.com/dashboard/projects"
step "Click 'New project' (create an organization first if you don't have one)."
step "Project name: anything recognizable, e.g. 'hone' or 'u15-ai-baserad-webbapplikation'."
step "Database Password: click 'Generate a password', then copy it into a"
step "password manager — you won't need to type it into this wizard, but"
step "you'll need it if you ever connect with psql or another DB client directly."
step "Region: pick one close to you (or to Vercel's deploy region)."
step "Plan: Free is fine for this project. Click 'Create new project'."
note "Provisioning takes ~2 minutes — wait for the project dashboard to load"
note "before continuing."
pause "Project created and provisioned?"

# ── Stage 2: direct connection (for migrations) ─────────────────────────
stage "Direct connection string (for migrations)"
say "drizzle-kit generate/migrate and 'npx auth@latest generate' need the"
say "direct connection, not the pooler (README §Database, src/lib/server/db/client.ts)."
step "In the project, open Project Settings (gear icon) → Database."
step "Under 'Connection string', select 'Direct connection' and the URI tab."
step "Click the reveal/eye icon so the real password is shown (not [YOUR-PASSWORD]),"
step "then copy the full postgres://... URI."
warn "If your network is IPv4-only, Supabase's direct connection (IPv6) may"
warn "be unreachable — use the 'Session pooler' string instead (same port 5432"
warn "semantics, IPv4-compatible)."
warn "Make sure it's the **Shared Pooler** tab, not 'Dedicated Pooler' — the"
warn "dedicated one needs a paid IPv4 add-on and fails the same way on a"
warn "free-plan/IPv4-only network (docs/research.md §4.3)."
ask_secret MIGRATION_DATABASE_URL "Paste the direct (or session pooler) connection URI:"
write_env MIGRATION_DATABASE_URL "$MIGRATION_DATABASE_URL"

# ── Stage 3: transaction pooler (for the running app) ───────────────────
stage "Transaction pooler connection string (for the running app)"
say "The running app (Better Auth + Drizzle's Postgres client) connects"
say "through the transaction-mode pooler, port 6543 — it does not support"
say "named prepared statements, which is why src/lib/server/db/client.ts"
say "passes 'prepare: false'."
step "Same Database settings page, select 'Transaction pooler' and the URI tab."
step "Reveal the real password and copy the full postgres://... URI (port 6543)."
warn "Same **Shared Pooler** vs. 'Dedicated Pooler' gotcha as above — the"
warn "dedicated one is paid-plan-only and needs the IPv4 add-on."
ask_secret DATABASE_URL "Paste the transaction pooler connection URI:"
write_env DATABASE_URL "$DATABASE_URL"

# ── Stage 4: apply the existing migrations ──────────────────────────────
stage "Apply migrations to Supabase"
say "Running 'npm run db:migrate' against MIGRATION_DATABASE_URL to create"
say "the schema from issue #21 (Better Auth tables + the app's own tables)."
if confirm "Run 'npm run db:migrate' now?"; then
  if npm run db:migrate; then
    printf '  %s✓ migrations applied%s\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("db:migrate failed — check MIGRATION_DATABASE_URL in $ENV_FILE and re-run: npm run db:migrate")
    warn "migration failed — see output above"
  fi
else
  SKIPPED+=("Migrations not yet applied — run: npm run db:migrate")
  warn "skipped — the app has no tables until this runs"
fi

# ── Stage 5: push the connection strings to Vercel ──────────────────────
stage "Push connection strings to Vercel (Production + Preview)"
say "scripts/vercel-connect-deploy.sh links and deploys the project but"
say "never sets env vars — without this, the deployed app has no DATABASE_URL."
if [[ ! -f .vercel/project.json ]]; then
  SKIPPED+=("Vercel env vars not set — this repo isn't linked yet; run scripts/vercel-connect-deploy.sh first, then re-run this wizard")
  warn "no .vercel/project.json found — run scripts/vercel-connect-deploy.sh first"
elif confirm "Push DATABASE_URL and MIGRATION_DATABASE_URL to Vercel (Production + Preview)?"; then
  _vercel_env_set() {
    local name="$1" value="$2" env="$3"
    $VERCEL env rm "$name" "$env" -y >/dev/null 2>&1 || true
    if printf '%s' "$value" | $VERCEL env add "$name" "$env" >/dev/null 2>&1; then
      printf '  %s✓ set%s Vercel env %s (%s)\n' "$GREEN" "$RESET" "$name" "$env"
    else
      SKIPPED+=("Vercel env $name ($env) — set manually: $VERCEL env add $name $env")
      warn "couldn't set Vercel env $name ($env)"
    fi
  }
  for env in production preview; do
    _vercel_env_set DATABASE_URL "$DATABASE_URL" "$env"
    _vercel_env_set MIGRATION_DATABASE_URL "$MIGRATION_DATABASE_URL" "$env"
  done
  note "Preview and Production share this one Supabase project/database for now."
else
  SKIPPED+=("Vercel env vars not set — run: $VERCEL env add DATABASE_URL production (and preview, and MIGRATION_DATABASE_URL)")
  warn "skipped — the deployed app will fail until these are set"
fi

# ── Stage 6: Better Auth's secret + base URL ─────────────────────────────
stage "Better Auth secret + base URL (issue #35)"
say "Better Auth refuses to start with its built-in default secret whenever"
say "NODE_ENV=production — which Vercel sets for Production *and* Preview"
say "builds. Without BETTER_AUTH_SECRET set, the first request to /api/auth/*"
say "throws in both (src/lib/auth-secret-guard.test.ts reproduces this)."
current_secret=$(_existing BETTER_AUTH_SECRET || true)
if [[ -n "$current_secret" ]]; then
  BETTER_AUTH_SECRET="$current_secret"
  note "reusing BETTER_AUTH_SECRET already in $ENV_FILE"
else
  BETTER_AUTH_SECRET=$(openssl rand -base64 32)
  write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
fi
ask BETTER_AUTH_URL "Production URL (the app's canonical domain, e.g. https://hone-green-rho.vercel.app):"
write_env BETTER_AUTH_URL "$BETTER_AUTH_URL"
note "Preview deploys get a different URL per branch/deployment, so"
note "BETTER_AUTH_URL is intentionally left unset there — Better Auth falls"
note "back to deriving the origin from each incoming request (a logged"
note "warning, not an error). See docs/adr/0004-better-auth-url-unset-on-preview.md."
if [[ ! -f .vercel/project.json ]]; then
  SKIPPED+=("Vercel env vars not set — this repo isn't linked yet; run scripts/vercel-connect-deploy.sh first, then re-run this wizard")
  warn "no .vercel/project.json found — run scripts/vercel-connect-deploy.sh first"
elif confirm "Push BETTER_AUTH_SECRET (Production + Preview) and BETTER_AUTH_URL (Production) to Vercel?"; then
  for env in production preview; do
    $VERCEL env rm BETTER_AUTH_SECRET "$env" -y >/dev/null 2>&1 || true
    if printf '%s' "$BETTER_AUTH_SECRET" | $VERCEL env add BETTER_AUTH_SECRET "$env" >/dev/null 2>&1; then
      printf '  %s✓ set%s Vercel env BETTER_AUTH_SECRET (%s)\n' "$GREEN" "$RESET" "$env"
    else
      SKIPPED+=("Vercel env BETTER_AUTH_SECRET ($env) — set manually: $VERCEL env add BETTER_AUTH_SECRET $env")
      warn "couldn't set Vercel env BETTER_AUTH_SECRET ($env)"
    fi
  done
  $VERCEL env rm BETTER_AUTH_URL production -y >/dev/null 2>&1 || true
  if printf '%s' "$BETTER_AUTH_URL" | $VERCEL env add BETTER_AUTH_URL production >/dev/null 2>&1; then
    printf '  %s✓ set%s Vercel env BETTER_AUTH_URL (production)\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("Vercel env BETTER_AUTH_URL (production) — set manually: $VERCEL env add BETTER_AUTH_URL production")
    warn "couldn't set Vercel env BETTER_AUTH_URL (production)"
  fi
else
  SKIPPED+=("Vercel env vars not set — run: $VERCEL env add BETTER_AUTH_SECRET production (and preview, and BETTER_AUTH_URL production)")
  warn "skipped — sign-in/sign-up will throw on first request in every deployed environment until this runs"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
