/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShellHistoryRouteImport } from './routes/_shell/history'
import { Route as ShellInterviewRouteImport } from './routes/_shell/interview'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellInterviewSessionIdRouteImport } from './routes/_shell/interview_.$sessionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellHistoryRoute = ShellHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInterviewRoute = ShellInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInterviewSessionIdRoute = ShellInterviewSessionIdRouteImport.update({
  id: '/interview_/$sessionId',
  path: '/interview/$sessionId',
  getParentRoute: () => ShellRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/history': typeof ShellHistoryRoute
  '/interview': typeof ShellInterviewRoute
  '/settings': typeof ShellSettingsRoute
  '/interview/$sessionId': typeof ShellInterviewSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/history': typeof ShellHistoryRoute
  '/interview': typeof ShellInterviewRoute
  '/settings': typeof ShellSettingsRoute
  '/interview/$sessionId': typeof ShellInterviewSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_shell/history': typeof ShellHistoryRoute
  '/_shell/interview': typeof ShellInterviewRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/interview_/$sessionId': typeof ShellInterviewSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/history'
    | '/interview'
    | '/settings'
    | '/interview/$sessionId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/history'
    | '/interview'
    | '/settings'
    | '/interview/$sessionId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/signup'
    | '/_shell/history'
    | '/_shell/interview'
    | '/_shell/settings'
    | '/_shell/interview_/$sessionId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/history': {
      id: '/_shell/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ShellHistoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/interview': {
      id: '/_shell/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof ShellInterviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/interview_/$sessionId': {
      id: '/_shell/interview_/$sessionId'
      path: '/interview/$sessionId'
      fullPath: '/interview/$sessionId'
      preLoaderRoute: typeof ShellInterviewSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellHistoryRoute: typeof ShellHistoryRoute
  ShellInterviewRoute: typeof ShellInterviewRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellInterviewSessionIdRoute: typeof ShellInterviewSessionIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellHistoryRoute: ShellHistoryRoute,
  ShellInterviewRoute: ShellInterviewRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellInterviewSessionIdRoute: ShellInterviewSessionIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
